Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'snippets/**/*'

Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion:
    2.5
  Exclude:
    - 'spec/spec_helper.rb'
